#ifndef _DEFENITIONS_H
#define _DEFENITIONS_H

	//Misc.
#define MOTOR_UPDATE_TIME 0.005
#define WATCHDOG_BISCUIT .1
#define INITIAL_DELAY 0
#define PRINT_DELAY 100
#define GYRO_KP .03

	//Autonomous 
#define RIGHT_DISTANCE_TO_TARGET 6730 //or 5371 if 360 encoder
#define LEFT_DISTANCE_TO_TARGET 6730 //or 5371 if 360 encoder
#define AUTONOMOUS_WAIT_TIME .5
#define AUTO_TIMER_TICKS 2.7
#define AUTO_DRIVE_RATE 3000 // approx. half speed


	//MotorBasedGrabber
#define GRABBER_SPEED_CONTROLLER 4
#define GRABBER_SPEED 0.01
#define GRABBER_STOP 0
#define GRABBER_STEP 0.1
#define GRABBER_MAX_SPEEED_FORWARD .9
#define GRABBER_MAX_SPEEED_REVERSE -.9
#define ZERO_SPEED_BUTTON 9
#define DECREASE_SPEED_BUTTON 10
#define INCREASE_SPEED_BUTTON 11

	//ThrowControl
#define	CATAPULT_SPEED_CONTROLLER 3 
#define THROW_STATE_DOWN 1
#define THROW_STATE_SETTLING 2
#define THROW_STATE_SHOOTING 3
#define THROW_STATE_RESETTING 4
#define CATAPULT_INITIAL_DISTANCE 0
#define CATAPULT_DISTANCE 330 //215
#define CATAPULT_BUFFER 5
#define CATAPULT_FORWARD_SPEED -0.8
#define CATAPULT_REVERSE_SPEED .1
#define CATAPULT_THROW_BUTTON 1 
#define CATAPULT_TIMER_TICKS .3 
#define CATAPULT_SETTLING_TIMER_TICKS .5 
#define CATAPULT_RESET_BUTTON 2
#define CATAPULT_TIMER_DOWN_TICKS 1.42
#define CATAPULT_SETTLING_SPEED -0.2
#define CATAPULT_SETTLING_DISTANCE 30
#define CATAPULT_DOWN_INPUT 5
#define CATAPULT_ENCODER_1 6
#define CATAPULT_ENCODER_2 7
#define MOTOR_OFF_SPEED 0

	//PistonBasedGrapper
// Controller Buttons: A=1, B=2, X=3, Y=4, LB=5, RB=6, Back=7
#define CLAMP_BUTTON 6
#define LIFT_BUTTON 5
#define CLAMP_PISTON_1 1
#define CLAMP_PISTON_2 2
#define LIFT_PISTON_1 3
#define LIFT_PISTON_2 4 
#define CLOSED_STATE 0
#define OPEN_STATE 1
#define DOWN_STATE 0
#define UP_STATE 1
#define BALL_DISTANCE .08
#define BALL_ULTRASONIC_CHANNEL 6 //1 maybe

	//Compressor
#define COMPRESSOR_RELAY 1
#define PRESSURE_SWITCH 1 

	//Robot Control
#define CONTROL_JOYSTICK 1
#define JOYSTICK_X_AXIS 1
#define JOYSTICK_Y_AXIS 2
#define LEFT_DRIVE_INPUT 2
#define RIGHT_DRIVE_INPUT 3
#define LEFT_MOTOR_SPEED_CONTROLLER 2 //2
#define RIGHT_MOTOR_SPEED_CONTROLLER 1 //1
#define RIGHT_MOTOR_ENCODER_1 9 // orig: pwm4
#define RIGHT_MOTOR_ENCODER_2 10 // orig: pwm5
#define LEFT_MOTOR_ENCODER_1 2
#define LEFT_MOTOR_ENCODER_2 3
#define TANK 1
#define ARCADE 2
#define LEFT_DRIVE_TOGGLE_1 7
#define LEFT_DRIVE_TOGGLE_2 8
#define RIGHT_DRIVE_TOGGLE_1 7
#define RIGHT_DRIVE_TOGGLE_2 8
#define NOT_TURNING 0
#define TURNING 1


	//Debug Levels
#define ROBOT_DEBUG 0 + SENSOR_TEST
#define LIFTER_STATE 2
#define CATAPULT_STATE 4
#define GRABBER_STATE 8
#define ENCODER_TEST 16
#define AUTONOMOUS_ENCODER_TEST 32
#define SENSOR_TEST 64


#endif
